# Site settings
title: Federal Privacy Council
description: Official Website of the US Federal Privacy Council
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.fpc.gov/" # the base hostname & protocol for your site
logo: /assets/img/logo-main.png
feature_image: /assets/img/feature-background.jpg
org_name: 18f
repo_name: federalist-modern-team-template

colors:
  background: '#ffffff'
  link:
    color: '#0071bc'
    active: '#0071bc'
    hover: '#205493'
    visited: '#0071bc'
  button:
    background: '#0071bc'
    hover: '#205493'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  reverse_text: '#ffffff'
  projects:
    accent: '#02bfe7'
    card-heading: '#0071bc'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    primary-background: '#f1f1f1'
    secondary-background: '#d6d7d9'
    text: '#212121'

analytics:
  google:
    code: # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - page
      - "project-list"
      - project
      - "team-list"
      - team

forms:
- type: newsletter
  heading: Sign up to receive updates from our team
  url: https://docs.google.com/forms/d/1Tsdm_2spbxWnmTFMrH5eHxpOAN9W4LB3eaMMXJ1N0rU/formResponse
  button: Subscribe
  privacypolicy: 
  fields:
    - type: email
      name: entry.1440502332
      label: Email Address
    - type: hidden
      name: fbzx
      value: -7861934959779167198

footer:
  links:
      - text: 
        href: 
      - text: 
        href: 
        image: 
  contact:
    name: 
    phonenumber: 
    email: 
    twitter:
      - 18f
    facebook: 
    youtube: 
    rss: 
  text: 
 # Change to a tag line for your agency

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

# Inititalize project and team collections
collections:
  projects:
    output: true
  team:
    output: true

wds-version: 1.1.0
